### ISSUE TITLE
The HTTP status is not included in beginSync

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-sdk-js#106]
https://github.com/rocicorp/replicache-sdk-js/blob/49b2ec9b35b464dbd5378d12a790a7e1e3a65a2f/src/replicache.ts#L272-L273

**Comment by phritz** [comment]
Should I prioritize adding it to beginsyncresponse?

**Comment by phritz** [comment]
@arv @aboodman we are not returning ClientViewInfo from the diffserver to repc: https://github.com/rocicorp/repc/blob/560ec4b7d318264400c8c45f0961026bedf20b88/src/sync/mod.rs#L348. The status code included in it is checked by repc, and since we don't have it repc does not fire its re-auth: https://rocicorp.slack.com/archives/C014J5KGBHP/p1601505714018600

Question: I _think_ the right thing to do is add it back in but first wanted to confirm that this is still the desired mechanism in repc to signal that the app needs to re-auth to the data layer?

**Comment by aboodman** [comment]
I don't feel strongly (anymore) about the shape of the rpc protocol here. I think the current JS API makes sense any anything that makes it work is fine with me.

**Comment by arv** [comment]
I agree that adding it back in is the right thing to do at this point.
